<a href="https://colab.research.google.com/github/rishika174/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/SQLTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SQL Database Operations on Student Records

This notebook demonstrates basic CRUD operations and data analysis using **SQLite** and **pandas** in Python:

*   **Database Setup:** Creates a `Students` table with fields for ID, Name, Course, Marks, and Semester.
*   **Data Insertion:** Populates the table with sample student records.
*   **Data Querying & Aggregation:**
    *   Filters students with marks greater than 80.
    *   Calculates the average marks grouped by each course.
    *   Filters students enrolled in semesters higher than 4.
    *   Identifies the top-performing student with the highest marks.
*   **Data Cleanup:** Demonstrates how to delete a specific record using a `WHERE` clause.

In [1]:
import sqlite3
import pandas as pd

# Create database
conn = sqlite3.connect("school.db")
cursor = conn.cursor()

# Drop table if it already exists
cursor.execute("DROP TABLE IF EXISTS Students")

# Create Students table
cursor.execute("""
CREATE TABLE Students (
    StudentID INTEGER PRIMARY KEY,
    Name TEXT,
    Course TEXT,
    Marks INTEGER,
    Semester INTEGER
)
""")

# Insert sample student data
students = [
    (1, "Riya", "Computer Science", 85, 3),
    (2, "Aman", "Mechanical", 78, 4),
    (3, "Neha", "Computer Science", 92, 5),
    (4, "Karan", "Electronics", 88, 6),
    (5, "Priya", "Civil", 81, 3),
    (6, "Arjun", "Mechanical", 75, 5),
    (7, "Sneha", "Computer Science", 95, 7),
    (8, "Vikram", "Civil", 83, 4)
]

In [2]:
cursor.executemany("INSERT INTO Students VALUES (?, ?, ?, ?, ?)", students)
conn.commit()

print("\nAll Students Data")
display(pd.read_sql("SELECT * FROM Students", conn))

All Students Data

   StudentID    Name            Course  Marks  Semester
0          1    Riya  Computer Science     85         3
1          2    Aman        Mechanical     78         4
2          3    Neha  Computer Science     92         5
3          4   Karan       Electronics     88         6
4          5   Priya             Civil     81         3
5          6   Arjun        Mechanical     75         5
6          7   Sneha  Computer Science     95         7
7          8  Vikram             Civil     83         4

In [3]:

print("\nStudents with Marks > 80")
display(pd.read_sql("""
SELECT Name, Marks
FROM Students
WHERE Marks > 80
""", conn))

Students with Marks > 80

     Name  Marks
0    Riya     85
1    Neha     92
2   Karan     88
3   Priya     81
4   Sneha     95
5  Vikram     83

In [4]:
print("\nAverage Marks by Course")
display(pd.read_sql("""
SELECT Course,
AVG(Marks) AS Average_Marks
FROM Students
GROUP BY Course
""", conn))

Average Marks by Course

             Course  Average_Marks
0             Civil      82.000000
1  Computer Science      90.666667
2       Electronics      88.000000
3        Mechanical      76.500000

In [5]:
print("\nStudents in Semester > 4")
display(pd.read_sql("""
SELECT *
FROM Students
WHERE Semester > 4
""", conn))

Students in Semester > 4

   StudentID   Name            Course  Marks  Semester
0          3   Neha  Computer Science     92         5
1          4  Karan       Electronics     88         6
2          6  Arjun        Mechanical     75         5
3          7  Sneha  Computer Science     95         7

In [6]:
print("\nStudent with the Highest Marks")
display(pd.read_sql("""
SELECT *
FROM Students
ORDER BY Marks DESC
LIMIT 1
""", conn))

Student with the Highest Marks

   StudentID   Name            Course  Marks  Semester
0          7  Sneha  Computer Science     95         7

In [7]:

# Delete a student record
cursor.execute("""
DELETE FROM Students
WHERE StudentID = 5
""")

conn.commit()
conn.close()